### PR TITLE
update doctrine/common dependency

### PR DESCRIPTION
**Pull request by ehibes**
`doctrine/common` is now on 3.4 so I made an update of composer.json file

### CODE REVIEW

**Comment by winzou** [comment]
Hi @ehibes Thanks for your PR. Could you keep allowing version 2.2? I would set the constraint as `"~2.2|~3.0"` Thanks!

**Comment by ehibes** [comment]
Hi @winzou I made the change.

**Comment by winzou** [comment]
Thanks!

**Comment by ehibes** [comment]
Thank you @winzou for accepting the PR, can you add a tag to update packagist/composer package?

**Pull request merged**
